export const members = [
  {
    id: 1,
    name: 'Bonnie Green',
    companyName: 'Green Realty',
    companySize: '10-50 employees',
    location: 'Jersey City, NJ',
    services: ['Residential Sales', 'Commercial Leases'],
    imageUrl: '/images/user/user-08.png',
    rating: 4,
    industry: 'Real Estate',
  },
  {
    id: 2,
    name: 'John Doe',
    companyName: 'Doe Real Estate',
    companySize: '50-200 employees',
    location: 'Newark, NJ',
    services: ['Industrial Brokerage', 'Investment Planning'],
    imageUrl: '/images/user/user-10.png',
    rating: 3,
    industry: 'Investment & Industrial',
  },
  {
    id: 3,
    name: 'Jane Smith',
    companyName: 'Smith Properties',
    companySize: '5-10 employees',
    location: 'Hoboken, NJ',
    services: ['Vacation Rentals', 'Property Management'],
    imageUrl: '/images/user/user-11.png',
    rating: 5,
    industry: 'Property Management',
  },
  {
    id: 4,
    name: 'Richard Roe',
    companyName: 'Roe Rentals',
    companySize: '200-500 employees',
    location: 'Princeton, NJ',
    services: ['Commercial Leasing', 'Tenant Representation'],
    imageUrl: '/images/user/user-02.png',
    rating: 2,
    industry: 'Commercial Real Estate',
  },
  {
    id: 5,
    name: 'Emily White',
    companyName: 'White Commercial',
    companySize: '50-200 employees',
    location: 'Trenton, NJ',
    services: ['Retail Property', 'Market Analysis'],
    imageUrl: '/images/user/user-03.png',
    rating: 3,
    industry: 'Retail & Market Analysis',
  },
  {
    id: 6,
    name: 'Chris Black',
    companyName: 'Black Homes',
    companySize: '10-50 employees',
    location: 'Atlantic City, NJ',
    services: ['Residential Sales', 'Foreclosures'],
    imageUrl: '/images/user/user-04.png',
    rating: 4,
    industry: 'Residential Real Estate',
  },
  {
    id: 7,
    name: 'Laura Blue',
    companyName: 'Blue Legal',
    companySize: '1-10 employees',
    location: 'Camden, NJ',
    services: ['Real Estate Law', 'Contract Drafting'],
    imageUrl: '/images/user/user-01.png',
    rating: 5,
    industry: 'Legal Services',
  },
  {
    id: 8,
    name: 'Oscar Yellow',
    companyName: 'Yellow Title',
    companySize: '20-50 employees',
    location: 'Cherry Hill, NJ',
    services: ['Title Insurance', 'Settlement Services'],
    imageUrl: '/images/user/user-12.png',
    rating: 3,
    industry: 'Title & Settlement',
  },
  {
    id: 9,
    name: 'Alice Grey',
    companyName: 'Grey Property Advisors',
    companySize: '50-200 employees',
    location: 'Morristown, NJ',
    services: ['Investment Advisory', 'Estate Planning'],
    imageUrl: '/images/user/user-07.png',
    rating: 4,
    industry: 'Investment & Planning',
  },
  {
    id: 10,
    name: 'Sam Red',
    companyName: 'Red Developers',
    companySize: '200-500 employees',
    location: 'Union, NJ',
    services: ['Land Development', 'Project Management'],
    imageUrl: '/images/user/user-08.png',
    rating: 5,
    industry: 'Development & Project Management',
  },
];
